### PR TITLE
Added the bottom fragments bar.

### PR DESCRIPTION
**Pull request by ashiskumarnaik**
Added the bottom fragments bar.( Design part )
Screenshot 2022-10-16 at 8 10 46 PM
Screenshot 2022-10-16 at 8 10 51 PM
Screenshot 2022-10-16 at 8 11 02 PM

#2 

Signed-off-by: Ashis Kumar Naik <ashishami2002@gmail.com>

### CODE REVIEW

**Comment by adityabisht02** [comment]
Nice!

**Comment by ashiskumarnaik** [comment]
@adityabisht02 Next we will do what happens when we click those button , what will be seen in those pages of that menu, 
expecting more issues from you?

**Comment by adityabisht02** [comment]
@ashiskumarnaik Could u explain how exactly you have created the bottom bar. I am planning on refactoring the codebase a bit cause it looks very messy right now.

**Comment by adityabisht02** [comment]
And yes there will be more issues also involving integration with the backend.

**Comment by adityabisht02** [comment]
@ashiskumarnaik Ok i understand what u have done. But this way every activity we have built will need to be a fragment. Ill get back to this tomorrow.

**Comment by ashiskumarnaik** [comment]
@adityabisht02 create a discord or slack or element chat group where we will discuss our ideas before implementing. I am willing to work more on this project.

**Comment by adityabisht02** [comment]
I'll create a discord then.

**Pull request merged**
